version: '2'
services:
  ldap:
    image: wancy/knox_titanrest_testing:knox
    command: /ldap.sh

  knox:
    image: wancy/knox_titanrest_testing:knox
    ports:
       - "8443:8443"
    command: /gateway.sh
    volumes:
       - ./topologies:/knox/conf/topologies
       - ./titan:/knox/data/services/titan
       - ./logs:/knox/logs
    depends_on:
       - ldap

  titan:
    image: wancy/titan-gremlin
    ports:
        - "8182:8182"
    command: /bin/bash 
       
