version: '2'
services:
  ldap:
    image: wancy/knox_titanrest_testing
    command: /ldap.sh

  knox:
    image: wancy/knox_titanrest_testing
    ports:
       - "8443:8443"
    command: /gateway.sh
    volumes:
       - ./topologies:/knox/conf/topologies
       - ./gremlin:/knox/data/services/gremlin
       - ./logs:/knox/logs
    depends_on:
       - ldap
    links:
       - gremlin

  gremlin:
    image: wancy/titan-gremlin
    ports:
        - "8182:8182"
       
